import Foundation

/// On-device rule-based certificate text matcher. Replaces the Foundation Models
/// classifier because Apple Intelligence on iOS 26.x AR locales throws
/// `An unsupported language or locale was used` whenever Arabic content (either in
/// the prompt instructions or in the user payload) is present. This matcher does
/// the same classification job using deterministic pattern matching — fast
/// (<1ms), testable, and fully on-device.
///
/// Architectural position: this is the verification *decision* layer. The warm
/// Hamoudi message shown to the user is generated by a separate copy layer
/// (Swift static fallback today; Captain API cloud enhancement tracked as
/// Phase 2). See `HamoudiVerificationReasoner` for the wiring.
///
/// Arabic normalization handles the typographic variations that certificates
/// commonly mix — hamza forms, alif forms, ya/ta marbuta, diacritics, tatweel.
enum CertificateTextMatcher {

    /// Reason codes kept identical to the former LM classifier's output so the
    /// downstream copy mapping (`HamoudiVerificationReasoner.hamoudiMessage`)
    /// doesn't need changes.
    enum ReasonCode: String {
        case verified
        case userAmbiguous = "user_ambiguous"
        case courseAmbiguous = "course_ambiguous"
        case bothAmbiguous = "both_ambiguous"
        case wrongCourse = "wrong_course"
        case imageUnclear = "image_unclear"
        case noCertificateText = "no_certificate_text"
    }

    struct Match: Sendable {
        let status: HamoudiVerificationStatus
        let reason: ReasonCode
        let confidence: Double
        let detectedCourseName: String?
        let detectedUserName: String?
    }

    /// Classifies the OCR text against the expected course + user first name.
    ///
    /// Decision ladder:
    /// 1. Text too short → `.imageUnclear`.
    /// 2. No certificate keywords anywhere → `.noCertificateText`.
    /// 3. Course matches + name matches → `.verified` (confidence ≥ 0.9).
    /// 4. Only course matches → `.userAmbiguous` (needs review).
    /// 5. Only name matches → `.courseAmbiguous` (needs review).
    /// 6. Neither matches (but certificate keywords present) → `.wrongCourse`.
    ///
    /// `nonisolated` so actors (e.g. `HamoudiVerificationReasoner`) can call it
    /// without a MainActor hop — this is pure string math, no shared state.
    nonisolated static func classify(
        extractedText: String,
        course: LearningCourse,
        userFirstName: String
    ) -> Match {
        // Minimum length — a certificate produces hundreds of OCR characters;
        // anything short is likely a blurry or misframed image.
        guard extractedText.count >= 30 else {
            return Match(
                status: .rejected,
                reason: .imageUnclear,
                confidence: 0.1,
                detectedCourseName: nil,
                detectedUserName: nil
            )
        }

        let ocr = normalize(extractedText)
        let courseAr = normalize(course.titleAr)
        let courseEn = normalize(course.titleEn)
        let name = normalize(userFirstName)

        // Require at least one certificate keyword so random text doesn't slip
        // through. Keyword list covers Arabic + English variants.
        let hasCertKeyword = Self.certificateKeywords.contains { keyword in
            ocr.contains(normalize(keyword))
        }
        guard hasCertKeyword else {
            return Match(
                status: .rejected,
                reason: .noCertificateText,
                confidence: 0.15,
                detectedCourseName: nil,
                detectedUserName: nil
            )
        }

        let courseMatch = fuzzyContains(haystack: ocr, needle: courseAr)
            || fuzzyContains(haystack: ocr, needle: courseEn)
        let nameMatch = !name.isEmpty && ocr.contains(name)

        switch (courseMatch, nameMatch) {
        case (true, true):
            return Match(
                status: .verified,
                reason: .verified,
                confidence: 0.92,
                detectedCourseName: course.titleAr,
                detectedUserName: userFirstName
            )
        case (true, false):
            return Match(
                status: .needsReview,
                reason: .userAmbiguous,
                confidence: 0.6,
                detectedCourseName: course.titleAr,
                detectedUserName: nil
            )
        case (false, true):
            return Match(
                status: .needsReview,
                reason: .courseAmbiguous,
                confidence: 0.55,
                detectedCourseName: nil,
                detectedUserName: userFirstName
            )
        case (false, false):
            return Match(
                status: .rejected,
                reason: .wrongCourse,
                confidence: 0.3,
                detectedCourseName: nil,
                detectedUserName: nil
            )
        }
    }

    // MARK: - Internals

    nonisolated private static let certificateKeywords: [String] = [
        "certificate", "certification", "completion", "awarded", "presented",
        "has successfully completed",
        "شهادة", "إتمام", "تمنح", "حضور"
    ]

    /// Arabic-aware normalization for robust substring comparison.
    ///
    /// Normalizations applied:
    /// - Lowercase Latin.
    /// - Strip combining diacritics (`.diacriticInsensitive` folding).
    /// - Unify hamza forms: أ إ آ → ا.
    /// - Unify ya forms: ى → ي.
    /// - Unify ta marbuta: ة → ه.
    /// - Remove tatweel (ـ).
    /// - Collapse runs of whitespace into single spaces.
    nonisolated static func normalize(_ s: String) -> String {
        var result = s.lowercased()
            .folding(options: .diacriticInsensitive, locale: nil)

        let replacements: [(String, String)] = [
            ("أ", "ا"),
            ("إ", "ا"),
            ("آ", "ا"),
            ("ى", "ي"),
            ("ة", "ه"),
            ("ـ", "")
        ]
        for (from, to) in replacements {
            result = result.replacingOccurrences(of: from, with: to)
        }

        return result
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespaces)
    }

    /// Substring match with a fuzzy prefix-anchor fallback. Catches cases where
    /// the OCR text contains a slightly different wording of the expected title.
    ///
    /// - Exact substring match → `true`
    /// - Reverse containment (`needle` contains `haystack`, with min length) → `true`
    /// - 70%-prefix of `needle` found in `haystack` → `true`
    nonisolated private static func fuzzyContains(haystack: String, needle: String) -> Bool {
        guard !needle.isEmpty else { return false }
        if haystack.contains(needle) { return true }
        if needle.count > 20, needle.contains(haystack) { return true }

        let anchorLen = max(Int(Double(needle.count) * 0.7), 10)
        guard anchorLen <= needle.count else { return false }
        let anchor = String(needle.prefix(anchorLen))
        return haystack.contains(anchor)
    }
}
