import XCTest
import ImageIO
import UniformTypeIdentifiers
@testable import AiQo

/// Verifies the privacy guarantees of the Kitchen vision pipeline:
/// 1. `PrivacySanitizer.sanitizeKitchenImageData` strips EXIF/GPS metadata.
/// 2. `PrivacySanitizer.sanitizeKitchenImageData` caps long-edge to ≤ 1280 px.
/// 3. Prompt sanitization (`sanitizePromptForCloud`) is callable for the
///    Kitchen prompt and preserves the hardcoded English text (no PII).
///
/// The end-to-end `CloudBrainService.generateKitchenAnalysis` call also
/// goes through `AICloudConsentGate.requireConsent()` + `TierGate` + a
/// network round-trip, which require coordinated singleton state that is
/// out of scope for a unit test. The contract those guard rails enforce
/// is verified by the sanitizer-level tests below.
final class KitchenVision_Sanitization_Test: XCTestCase {

    private let sanitizer = PrivacySanitizer()

    // MARK: - EXIF / GPS stripping

    func testSanitizeKitchenImageDataStripsGPSAndUserEXIFFields() throws {
        // ImageIO sometimes writes a *technical* EXIF block (color profile,
        // pixel dimensions, encoding metadata) to JPEGs by default — that is
        // not PII and not what we're guarding against. The actual privacy
        // contract is: GPS coordinates and user-identifying EXIF fields
        // (date/time taken, camera/lens model, device serial, etc.) must
        // never leave the device.
        let imageWithMetadata = try makeJPEGWithEXIFAndGPS()

        let clean = sanitizer.sanitizeKitchenImageData(imageWithMetadata)
        let cleanData = try XCTUnwrap(clean, "Sanitizer must return non-nil for a valid JPEG.")

        let cleanMetadata = readMetadata(from: cleanData)

        // GPS is pure PII — never auto-generated by ImageIO, so a non-nil
        // GPS dict in the output would mean the sanitizer leaked input data.
        XCTAssertNil(cleanMetadata[kCGImagePropertyGPSDictionary as String],
                     "GPS coordinates must be stripped from outbound image.")

        // If a (technical) EXIF dict survives, it must not contain user
        // fields. Auto-generated technical EXIF (ColorSpace, PixelXDimension)
        // is fine; user fields are not.
        if let exif = cleanMetadata[kCGImagePropertyExifDictionary as String] as? [String: Any] {
            XCTAssertNil(exif[kCGImagePropertyExifDateTimeOriginal as String],
                         "User-identifying EXIF (DateTimeOriginal) must not survive.")
            XCTAssertNil(exif[kCGImagePropertyExifLensModel as String],
                         "User-identifying EXIF (LensModel) must not survive.")
            XCTAssertNil(exif[kCGImagePropertyExifBodySerialNumber as String],
                         "User-identifying EXIF (BodySerialNumber) must not survive.")
        }

        // TIFF block can carry Make/Model/Software — same PII concern.
        if let tiff = cleanMetadata[kCGImagePropertyTIFFDictionary as String] as? [String: Any] {
            XCTAssertNil(tiff[kCGImagePropertyTIFFMake as String],
                         "Camera Make must not survive sanitization.")
            XCTAssertNil(tiff[kCGImagePropertyTIFFModel as String],
                         "Camera Model must not survive sanitization.")
        }
    }

    // MARK: - Dimension cap

    func testSanitizeKitchenImageDataResizesAboveMax() throws {
        let oversize = try makeJPEG(width: 4000, height: 3000)
        let clean = try XCTUnwrap(sanitizer.sanitizeKitchenImageData(oversize))

        guard let source = CGImageSourceCreateWithData(clean as CFData, nil),
              let cgImage = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
            XCTFail("Sanitized output must decode as a valid image.")
            return
        }

        let longEdge = max(cgImage.width, cgImage.height)
        XCTAssertLessThanOrEqual(longEdge, 1280,
                                 "Sanitized image must cap long-edge at 1280 px. Got \(longEdge).")
    }

    func testSanitizeKitchenImageDataLeavesUndersizedAlone() throws {
        let undersized = try makeJPEG(width: 800, height: 600)
        let clean = try XCTUnwrap(sanitizer.sanitizeKitchenImageData(undersized))

        guard let source = CGImageSourceCreateWithData(clean as CFData, nil),
              let cgImage = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
            XCTFail("Sanitized output must decode as a valid image.")
            return
        }

        // Resize on already-small images is still a re-encode (which strips EXIF),
        // but the dimensions should not exceed the original long edge.
        let longEdge = max(cgImage.width, cgImage.height)
        XCTAssertLessThanOrEqual(longEdge, 1280)
    }

    // MARK: - nil safety

    func testSanitizeKitchenImageDataReturnsNilOnNilInput() {
        XCTAssertNil(sanitizer.sanitizeKitchenImageData(nil),
                     "nil input must produce nil output (caller handles this as an error).")
    }

    func testSanitizeKitchenImageDataReturnsNilOnGarbage() {
        let garbage = Data([0x00, 0x01, 0x02, 0x03])
        XCTAssertNil(sanitizer.sanitizeKitchenImageData(garbage),
                     "Non-image bytes must return nil rather than producing a broken image.")
    }

    // MARK: - Prompt sanitization wiring

    func testKitchenPromptPassesThroughSanitizer() {
        // The Kitchen prompt today has no PII, but the canonical pipeline
        // still routes it through sanitizePromptForCloud so future prompt
        // edits stay safe. This test pins that contract.
        let prompt = "Return JSON only. Visible food items only."
        let result = sanitizer.sanitizePromptForCloud(prompt, knownUserName: nil)
        XCTAssertFalse(result.isEmpty, "Sanitizer must not eat the hardcoded prompt.")
        // The prompt is whitespace-normalized, so leading "Return" survives intact.
        XCTAssertTrue(result.contains("Return JSON only"),
                      "Hardcoded prompt text must survive sanitization. Got: \(result)")
    }

    func testKitchenPromptWithInjectedEmailIsScrubbed() {
        // Hypothetical: a future prompt edit interpolates user input.
        // The sanitizer must still strip PII.
        let promptWithPII = "Analyze fridge for user@example.com. Return JSON."
        let result = sanitizer.sanitizePromptForCloud(promptWithPII, knownUserName: nil)
        XCTAssertFalse(result.contains("user@example.com"),
                       "Email must not survive prompt sanitization: \(result)")
    }

    // MARK: - Helpers

    /// Builds a real JPEG byte stream with both EXIF and GPS dictionaries
    /// attached. Used to verify the sanitizer actually strips them.
    private func makeJPEGWithEXIFAndGPS() throws -> Data {
        let bitmap = try makeSolidColorCGImage(width: 200, height: 200)
        let destinationData = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            destinationData,
            UTType.jpeg.identifier as CFString,
            1,
            nil
        ) else {
            throw NSError(domain: "test", code: 1)
        }

        let properties: [CFString: Any] = [
            kCGImagePropertyExifDictionary: [
                kCGImagePropertyExifDateTimeOriginal: "2024:01:01 12:00:00",
                kCGImagePropertyExifLensModel: "TestLens 50mm"
            ],
            kCGImagePropertyGPSDictionary: [
                kCGImagePropertyGPSLatitude: 37.7749,
                kCGImagePropertyGPSLatitudeRef: "N",
                kCGImagePropertyGPSLongitude: 122.4194,
                kCGImagePropertyGPSLongitudeRef: "W"
            ]
        ]

        CGImageDestinationAddImage(destination, bitmap, properties as CFDictionary)
        guard CGImageDestinationFinalize(destination) else {
            throw NSError(domain: "test", code: 2)
        }
        return destinationData as Data
    }

    private func makeJPEG(width: Int, height: Int) throws -> Data {
        let bitmap = try makeSolidColorCGImage(width: width, height: height)
        let destinationData = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            destinationData,
            UTType.jpeg.identifier as CFString,
            1,
            nil
        ) else {
            throw NSError(domain: "test", code: 1)
        }
        CGImageDestinationAddImage(destination, bitmap, nil)
        guard CGImageDestinationFinalize(destination) else {
            throw NSError(domain: "test", code: 2)
        }
        return destinationData as Data
    }

    private func makeSolidColorCGImage(width: Int, height: Int) throws -> CGImage {
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        let bytesPerPixel = 4
        let bytesPerRow = width * bytesPerPixel
        var pixels = [UInt8](repeating: 200, count: width * height * bytesPerPixel)
        for i in stride(from: 3, to: pixels.count, by: 4) {
            pixels[i] = 255 // alpha
        }

        guard let provider = CGDataProvider(data: Data(pixels) as CFData) else {
            throw NSError(domain: "test", code: 3)
        }

        guard let image = CGImage(
            width: width,
            height: height,
            bitsPerComponent: 8,
            bitsPerPixel: 32,
            bytesPerRow: bytesPerRow,
            space: colorSpace,
            bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue),
            provider: provider,
            decode: nil,
            shouldInterpolate: false,
            intent: .defaultIntent
        ) else {
            throw NSError(domain: "test", code: 4)
        }
        return image
    }

    private func readMetadata(from data: Data) -> [String: Any] {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [String: Any] else {
            return [:]
        }
        return props
    }
}
