import Foundation

// MARK: - Cross-process Kernel state
//
// This file is compiled into the main app AND all three Kernel extensions
// (DeviceActivityMonitor / ShieldConfiguration / ShieldAction). It must stay
// dependency-free beyond Foundation + `AppGroupKeys` so every target can build
// it. No shielding / blocking behavior lives here — Phase 1 is state only.

/// What the user must do for the Kernel to unlock. Phase 1 models the
/// "unlock by physical activity (steps)" requirement only; persisted
/// cross-process so an extension can read what the user configured in the app.
struct KernelUnlockRequirement: Codable, Equatable, Sendable {
    enum Kind: String, Codable, Sendable {
        case steps
    }

    var kind: Kind
    /// Step goal that must be reached to satisfy the requirement.
    var stepGoal: Int

    init(kind: Kind = .steps, stepGoal: Int) {
        self.kind = kind
        self.stepGoal = stepGoal
    }
}

/// The Kernel's protection mode. Shared cross-process so the DeviceActivity
/// monitor and shield extensions read the same mode the app set.
enum KernelProtectionMode: String, Codable, Sendable {
    /// Shield applies after the chosen apps cross a daily usage threshold
    /// **and** the user is sedentary (Phase 3 doomscroll gate).
    case smart
    /// Shield applies immediately and stays on.
    case hard
}

/// A typed, graded unlock challenge the user completes (with their body) to lift
/// the shield. Generated by `UnlockChallengeGenerator` from the live
/// `DoomscrollState` + time of day, then frozen into `KernelState`. Shared
/// cross-process (lives in this file so it compiles into every target).
struct UnlockChallenge: Codable, Equatable, Sendable {
    enum Kind: Codable, Equatable, Sendable {
        /// Walk this many steps (the universal, iPhone-only path).
        case steps(Int)
        /// Follow a guided breathing animation for this many seconds.
        case breathing(seconds: Int)
        /// Keep heart rate at/below `maxBPM` for `holdSeconds` (Apple Watch only).
        case calmHeartRate(maxBPM: Int, holdSeconds: Int)
    }

    enum Difficulty: String, Codable, Sendable { case easy, medium, hard, emergency }

    var kind: Kind
    var difficulty: Difficulty
    /// Earned coins required to bypass by spending (via the real `CoinManager`).
    var coinPrice: Int

    /// Step target, or 0 for non-step challenges.
    var stepTarget: Int {
        if case let .steps(n) = kind { return n }
        return 0
    }
}

/// A single Codable snapshot of everything the Kernel feature shares between the
/// main app and its three extensions. Persisted as one JSON blob in the App
/// Group so every process reads the same source of truth.
///
/// Decoding is tolerant (see the `init(from:)` extension): every field falls back
/// to a default, so a blob written by an earlier build still loads (keeps the
/// user's chosen apps across upgrades).
struct KernelState: Codable, Equatable, Sendable {
    /// Encoded `FamilyActivitySelection` (apps / categories / webDomains tokens).
    /// Kept as opaque `Data` so this shared type stays free of the FamilyControls
    /// framework — the app encodes the selection, the extensions decode it.
    var selectionData: Data?

    // MARK: Protection (Phase 2)
    /// Master on/off for shielding (reuses the v1 `isProtectionEnabled` concept).
    var isProtectionEnabled: Bool
    /// Smart (usage-threshold) vs Hard (always-on).
    var mode: KernelProtectionMode
    /// SMART daily usage threshold, in minutes, before the shield applies.
    /// Adjustable (floor 1) for testing.
    var usageThresholdMinutes: Int

    /// Whether the chosen apps are currently shielded.
    var isLocked: Bool

    // MARK: Temporary unlock (Phase 2 testing; real steps-unlock = Phase 3)
    /// True while a temporary unlock window is open.
    var isUnlocked: Bool
    /// When the temporary unlock expires; re-shield fires at/after this.
    var unlockExpiry: Date?

    /// What the user must do to unlock for real (Phase 3: steps).
    var unlock: KernelUnlockRequirement?

    /// 0...1 "kernel charge" — grows when the user completes a real challenge.
    var chargeLevel: Double

    /// Active lock-session window (set when a session begins / expires).
    var sessionStart: Date?
    var sessionExpiry: Date?

    // MARK: Bio engine (Phase 3)
    /// True when the user is sedentary (no recent step increase). Written by the
    /// app's bio engine; READ by the monitor to gate SMART blocking (walk-while-
    /// using must NOT block).
    var doomscrollSedentary: Bool
    /// Timestamp the shield was applied; the app counts steps since this instant
    /// (via HealthKit) to verify a steps challenge.
    var unlockBaselineAt: Date?
    /// The frozen challenge for the current lock (generated by the app).
    var activeChallenge: UnlockChallenge?
    /// Opens (unlocks) recorded today + the day key used to reset the counter.
    var shieldsOpenedToday: Int
    var shieldsOpenedDayKey: String?
    /// Daily cap on opens before the "loving stop" (default 3).
    var dailyShieldLimit: Int
    /// Day key on which the once-a-day emergency exit was consumed.
    var emergencyUsedDayKey: String?

    // MARK: Escalation — 5 rising shields + an infinite, gentle tail
    /// How many shields have FIRED today (1-based once the first applies) + the day
    /// key used to reset it at the local day boundary. Drives the rising difficulty
    /// (steps / session length / energy cost) via `KernelEscalation`. Distinct from
    /// `shieldsOpenedToday` (successful unlocks): this counts shields APPLIED.
    var shieldsTriggeredToday: Int
    var shieldsTriggeredDayKey: String?

    /// User's language ("ar"/"en"), mirrored here so the shield extension (a
    /// separate bundle that can't read the app's UserDefaults) can localize.
    var languageCode: String

    static let empty = KernelState(
        selectionData: nil,
        isProtectionEnabled: false,
        mode: .smart,
        usageThresholdMinutes: 30,
        isLocked: false,
        isUnlocked: false,
        unlockExpiry: nil,
        unlock: nil,
        chargeLevel: 0,
        sessionStart: nil,
        sessionExpiry: nil,
        doomscrollSedentary: false,
        unlockBaselineAt: nil,
        activeChallenge: nil,
        shieldsOpenedToday: 0,
        shieldsOpenedDayKey: nil,
        dailyShieldLimit: 3,
        emergencyUsedDayKey: nil,
        shieldsTriggeredToday: 0,
        shieldsTriggeredDayKey: nil,
        languageCode: "ar"
    )
}

extension KernelState {
    /// Tolerant decoder: every field is decoded-if-present with a default so a
    /// blob written by an older build (with fewer keys) still decodes instead of
    /// throwing — which would otherwise reset the user's selection.
    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = KernelState.empty
        selectionData         = try c.decodeIfPresent(Data.self, forKey: .selectionData) ?? d.selectionData
        isProtectionEnabled   = try c.decodeIfPresent(Bool.self, forKey: .isProtectionEnabled) ?? d.isProtectionEnabled
        mode                  = try c.decodeIfPresent(KernelProtectionMode.self, forKey: .mode) ?? d.mode
        usageThresholdMinutes = try c.decodeIfPresent(Int.self, forKey: .usageThresholdMinutes) ?? d.usageThresholdMinutes
        isLocked              = try c.decodeIfPresent(Bool.self, forKey: .isLocked) ?? d.isLocked
        isUnlocked            = try c.decodeIfPresent(Bool.self, forKey: .isUnlocked) ?? d.isUnlocked
        unlockExpiry          = try c.decodeIfPresent(Date.self, forKey: .unlockExpiry) ?? d.unlockExpiry
        unlock                = try c.decodeIfPresent(KernelUnlockRequirement.self, forKey: .unlock) ?? d.unlock
        chargeLevel           = try c.decodeIfPresent(Double.self, forKey: .chargeLevel) ?? d.chargeLevel
        sessionStart          = try c.decodeIfPresent(Date.self, forKey: .sessionStart) ?? d.sessionStart
        sessionExpiry         = try c.decodeIfPresent(Date.self, forKey: .sessionExpiry) ?? d.sessionExpiry
        doomscrollSedentary   = try c.decodeIfPresent(Bool.self, forKey: .doomscrollSedentary) ?? d.doomscrollSedentary
        unlockBaselineAt      = try c.decodeIfPresent(Date.self, forKey: .unlockBaselineAt) ?? d.unlockBaselineAt
        activeChallenge       = try c.decodeIfPresent(UnlockChallenge.self, forKey: .activeChallenge) ?? d.activeChallenge
        shieldsOpenedToday    = try c.decodeIfPresent(Int.self, forKey: .shieldsOpenedToday) ?? d.shieldsOpenedToday
        shieldsOpenedDayKey   = try c.decodeIfPresent(String.self, forKey: .shieldsOpenedDayKey) ?? d.shieldsOpenedDayKey
        dailyShieldLimit      = try c.decodeIfPresent(Int.self, forKey: .dailyShieldLimit) ?? d.dailyShieldLimit
        emergencyUsedDayKey   = try c.decodeIfPresent(String.self, forKey: .emergencyUsedDayKey) ?? d.emergencyUsedDayKey
        shieldsTriggeredToday = try c.decodeIfPresent(Int.self, forKey: .shieldsTriggeredToday) ?? d.shieldsTriggeredToday
        shieldsTriggeredDayKey = try c.decodeIfPresent(String.self, forKey: .shieldsTriggeredDayKey) ?? d.shieldsTriggeredDayKey
        languageCode          = try c.decodeIfPresent(String.self, forKey: .languageCode) ?? d.languageCode
    }
}

/// Thread-safe reader/writer for `KernelState`, backed by App Group UserDefaults
/// (`AppGroupKeys.kernelState`). Compiled into the main app **and** all three
/// extensions so they share one implementation and one source of truth.
final class KernelSharedStore: @unchecked Sendable {
    static let shared = KernelSharedStore()

    private let lock = NSLock()
    private let defaults: UserDefaults?
    private let key = AppGroupKeys.kernelState

    init(defaults: UserDefaults? = AppGroupKeys.defaults()) {
        self.defaults = defaults
    }

    /// Current snapshot (never throws; returns `.empty` when unset or unreadable).
    func load() -> KernelState {
        lock.lock(); defer { lock.unlock() }
        guard let data = defaults?.data(forKey: key) else { return .empty }
        return (try? JSONDecoder().decode(KernelState.self, from: data)) ?? .empty
    }

    /// Persist a full snapshot.
    func save(_ state: KernelState) {
        lock.lock(); defer { lock.unlock() }
        guard let data = try? JSONEncoder().encode(state) else { return }
        defaults?.set(data, forKey: key)
    }

    /// Atomic read-modify-write. Returns the state after mutation.
    @discardableResult
    func mutate(_ body: (inout KernelState) -> Void) -> KernelState {
        lock.lock(); defer { lock.unlock() }
        var state: KernelState
        if let data = defaults?.data(forKey: key),
           let decoded = try? JSONDecoder().decode(KernelState.self, from: data) {
            state = decoded
        } else {
            state = .empty
        }
        body(&state)
        if let data = try? JSONEncoder().encode(state) {
            defaults?.set(data, forKey: key)
        }
        return state
    }

    // MARK: - FamilyActivitySelection blob convenience

    /// The raw encoded `FamilyActivitySelection` the app last persisted.
    var selectionData: Data? { load().selectionData }

    /// Replace just the encoded selection blob.
    func setSelectionData(_ data: Data?) {
        mutate { $0.selectionData = data }
    }

    // MARK: - Protection state (Phase 2)

    func enableProtection(mode: KernelProtectionMode) {
        mutate {
            $0.isProtectionEnabled = true
            $0.mode = mode
            $0.isUnlocked = false
            $0.unlockExpiry = nil
        }
    }

    func disableProtection() {
        mutate {
            $0.isProtectionEnabled = false
            $0.isUnlocked = false
            $0.unlockExpiry = nil
            $0.isLocked = false
        }
    }

    func setMode(_ mode: KernelProtectionMode) {
        mutate { $0.mode = mode }
    }

    func setUsageThreshold(minutes: Int) {
        mutate { $0.usageThresholdMinutes = max(1, minutes) }
    }

    /// Grant an earned access session: lift the shield and open a timed window.
    /// In Phase 3 this is called by `KernelBioEngine` after the user completes a
    /// real challenge (walk/breath/calm) or spends earned coins — replacing the
    /// Phase-2 temporary-unlock button. Re-block after the window reuses the
    /// existing 3-layer `reshieldIfNeeded` guard (keyed on `unlockExpiry`).
    func grantUnlock(minutes: Double) {
        let expiry = Date().addingTimeInterval(minutes * 60)
        mutate {
            $0.isUnlocked = true
            $0.unlockExpiry = expiry
            $0.isLocked = false
        }
        KernelShieldController.shared.clearShield()
    }

    // MARK: - Bio engine + challenge (Phase 3)

    /// Stable per-day key (local calendar) used to reset daily counters.
    func todayKey() -> String {
        let cal = Calendar.current
        let day = cal.startOfDay(for: Date())
        return "\(cal.component(.year, from: day))-\(cal.component(.month, from: day))-\(cal.component(.day, from: day))"
    }

    /// Sedentary gate flag — written by the app, read by the monitor.
    func setDoomscrollSedentary(_ value: Bool) {
        mutate { $0.doomscrollSedentary = value }
    }

    /// Mirror the app's language so the shield extension can localize.
    func setLanguageCode(_ code: String) {
        mutate { $0.languageCode = code }
    }

    /// Freeze the generated challenge for the current lock. The step-baseline is
    /// stamped separately by `KernelShieldController.applyShield` at block time.
    func setActiveChallenge(_ challenge: UnlockChallenge) {
        mutate { $0.activeChallenge = challenge }
    }

    /// Opens already used today (0 if the stored day key is stale).
    func openedTodayCount() -> Int {
        let s = load()
        return s.shieldsOpenedDayKey == todayKey() ? s.shieldsOpenedToday : 0
    }

    /// Escalation index — how many shields have FIRED today (1-based once the first
    /// applies; 0 when the stored day key is stale, so the first shield of a new day
    /// restarts the ramp). The counter is incremented atomically by
    /// `KernelShieldController.applyShield` on each fresh lock transition, and shared
    /// cross-process via the App Group so the extensions and the app agree on the
    /// current shield number within the same day (and after a relaunch).
    func triggeredTodayCount() -> Int {
        let s = load()
        return s.shieldsTriggeredDayKey == todayKey() ? s.shieldsTriggeredToday : 0
    }

    /// True once today's opens have hit the daily cap (the "loving stop").
    func dailyLimitReached() -> Bool {
        openedTodayCount() >= max(1, load().dailyShieldLimit)
    }

    /// Record a successful open: bump today's counter (with daily reset) and
    /// clear the per-lock challenge + baseline. Returns the new count.
    @discardableResult
    func recordShieldOpened() -> Int {
        let key = todayKey()
        return mutate {
            if $0.shieldsOpenedDayKey != key {
                $0.shieldsOpenedDayKey = key
                $0.shieldsOpenedToday = 0
            }
            $0.shieldsOpenedToday += 1
            $0.activeChallenge = nil
            $0.unlockBaselineAt = nil
        }.shieldsOpenedToday
    }

    /// The once-a-day emergency exit is available until consumed.
    func emergencyAvailable() -> Bool {
        load().emergencyUsedDayKey != todayKey()
    }

    func markEmergencyUsed() {
        let key = todayKey()
        mutate { $0.emergencyUsedDayKey = key }
    }

    /// Grow the kernel charge (capped at 1.0) — the only Kernel reward besides
    /// the single fixed coin bonus; steps still earn coins via the existing loop.
    func addCharge(_ amount: Double) {
        mutate { $0.chargeLevel = min(1.0, max(0, $0.chargeLevel + amount)) }
    }
}
